apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: minikube-postgres-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi