apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  DATABASE_USER: cG9zdGdyZXM=
  DATABASE_PASS: cG9zdGdyZXM=
  MP_ACCESS_TOKEN: <base64-encoded-token> # Adicione aqui o token de integração do Mercado Pago em base64